<a href="https://colab.research.google.com/github/Leo278V/Final-Assignment-PDS/blob/Final-Assignment-V2/Final-Assignment-V2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Rule Based Approach

In [18]:
import pandas as pd
import numpy as np

In [8]:
# Data Path CSV Files

data_path_department = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Final-Assignment-V2/department-v2.csv?token=GHSAT0AAAAAADQCRM6W33FX6JAZTU3E4GNC2KJBWIQ"
df_department = pd.read_csv(data_path_department)
df_department.head()

                                               text               label
0                   Adjoint directeur communication           Marketing
1                     Advisor Strategy and Projects  Project Management
2                               Beratung & Projekte  Project Management
3                      Beratung & Projektmanagement  Project Management
4  Beratung und Projektmanagement kommunale Partner  Project Management

In [9]:
data_path_seniority = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Final-Assignment-V2/seniority-v2.csv?token=GHSAT0AAAAAADQCRM6X7NSLPC6XU2WSLJAU2KJBX6A"
df_seniortiy = pd.read_csv(data_path_seniority)
df_seniortiy.head()

                                text   label
0                            Analyst  Junior
1                 Analyste financier  Junior
2  Anwendungstechnischer Mitarbeiter  Junior
3               Application Engineer  Senior
4              Applications Engineer  Senior

In [17]:
# Data Path Annotated LinkedIN Profiles
data_path_profiles = "https://raw.githubusercontent.com/Leo278V/Final-Assignment-PDS/refs/heads/Final-Assignment-V2/linkedin_experience_annotated.csv?token=GHSAT0AAAAAADQCRM6WQ2VITJLKQHBMMK442KJCA7A"
df_profiles = pd.read_csv(data_path_profiles)
df_profiles.head()

,organization,linkedin,position,startDate,endDate,status,department,seniority,person_id
0,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokurist,2019-08,NaN,ACTIVE,Other,Management,0
1,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,NaN,ACTIVE,Other,Management,0
2,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Betriebswirtin,2019-07,NaN,ACTIVE,Other,Professional,0
3,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokuristin,2019-07,NaN,ACTIVE,Other,Management,0
4,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,NaN,ACTIVE,Other,Management,0

In [32]:
# Filtering for active
df_active = df_profiles[df_profiles["status"] == "ACTIVE"].copy()

df_active.head()

,organization,linkedin,position,startDate,endDate,status,department,seniority,person_id
0,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokurist,2019-08,NaN,ACTIVE,Other,Management,0
1,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,NaN,ACTIVE,Other,Management,0
2,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Betriebswirtin,2019-07,NaN,ACTIVE,Other,Professional,0
3,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,Prokuristin,2019-07,NaN,ACTIVE,Other,Management,0
4,Depot4Design GmbH,https://www.linkedin.com/company/depot4design-...,CFO,2019-07,NaN,ACTIVE,Other,Management,0

In [45]:
# Creating Dicitionaries

#Seniority
seniority_dict = (
    df_seniortiy
    .dropna(subset=["text", "label"])
    .assign(keyword=lambda x: x["text"].str.lower())
    .set_index("keyword")["label"]
    .to_dict()
)

#Department
department_dict = (
    df_department
    .dropna(subset=["text", "label"])
    .assign(keyword=lambda x: x["text"].str.lower())
    .set_index("keyword")["label"]
    .to_dict()
)
print(seniority_dict)
print(department_dict)

{'analyst': 'Junior', 'analyste financier': 'Junior', 'anwendungstechnischer mitarbeiter': 'Junior', 'application engineer': 'Senior', 'applications engineer': 'Senior', 'architecte si - chef de projet applicatif': 'Lead', 'associate': 'Junior', 'associate - research': 'Junior', 'associate partner': 'Junior', 'associate recruiter': 'Junior', 'associated partner': 'Junior', 'bi analyst': 'Junior', 'call-center-agent- service - mitarbeiter': 'Junior', 'chargée de communication / chef de projet événementiel': 'Lead', 'chef de marché résidences services senior - solutions logicielles métier': 'Lead', 'chef de projet': 'Lead', 'chef de projet communication et marketing': 'Lead', 'chef de projet erp': 'Lead', 'chef de projet évènementiel': 'Lead', 'chef de projet événementiel / event coordinator': 'Lead', 'chef de projet marketing': 'Lead', 'chef de projet marketing digital': 'Lead', 'chef de projet marketing digital senior': 'Lead', 'chef de projet marketing et communication': 'Lead', 'chef de projet systèmes et services': 'Lead', 'chef de projets marketing': 'Lead', 'chef des ventes': 'Lead', 'chef des ventes france': 'Lead', 'chef des ventes ouest': 'Lead', 'chef des ventes sm3 claas': 'Lead', 'clinical research associate ii': 'Junior', 'cloud systems analyst': 'Junior', 'commercial team leader sales and marketing europe': 'Lead', 'data analyst': 'Junior', 'data analyst - monetization and payment': 'Junior', 'data engineering & visualization': 'Senior', "devops as a service. we're hiring engineers in north america": 'Senior', 'directeur commercial - responsable filiale europe du sud / groupe econtrols': 'Senior', 'directeur de projets et responsable des infrastructures informatiques': 'Senior', 'engineer': 'Senior', 'group leader in energy impact research': 'Lead', 'investment analyst': 'Junior', 'lead engineer': 'Senior', 'lead solution engineer': 'Senior', 'market- and customer analyst': 'Junior', 'market research analyst': 'Junior', 'microsoft system engineering': 'Senior', 'mitarbeiter': 'Junior', 'mitarbeiter auftragsabwicklung': 'Junior', 'mitarbeiter customer service': 'Junior', 'mitarbeiter datenmanagement': 'Junior', 'mitarbeiter projektmanagement': 'Junior', 'mitarbeiter verkaufsinnendienst': 'Junior', 'mitarbeiterin event- und kundenmanagement': 'Junior', 'mitarbeiterin in der verwaltung': 'Junior', 'mitarbeiterin presse- und öffentlichkeitsarbeit': 'Junior', 'presales associate': 'Junior', 'principal cloud engineer': 'Senior', 'project engineer': 'Senior', 'pr-referent': 'Junior', 'pr-referentin': 'Junior', 'recruiting analyst': 'Junior', 'referent': 'Junior', 'referent (projektmanager)': 'Junior', 'referent cafm / sharepoint': 'Junior', 'referent grundsatzfragen': 'Junior', 'referent kompetenzfeld erzeugung & infrastruktur': 'Junior', 'referent öffentlichkeitsarbeit': 'Junior', 'referent unternehmenskommunikation': 'Junior', 'referent werbung & veranstaltung': 'Junior', 'referentin abteilung ausstellungen': 'Junior', 'referentin eventmanagement': 'Junior', 'referentin für prozess- und projektmanagement': 'Junior', 'referentin für unternehmensentwicklung und vert...': 'Junior', 'referentin für unternehmenskommunikation': 'Junior', 'referentin für veranstaltungsmanagement': 'Junior', 'referentin öffentlichkeitsarbeit': 'Junior', 'referentin onlinemarketing': 'Junior', 'referentin pr und unternehmenskommunikation dach': 'Junior', 'referentin presse- und öffentlichkeitsarbeit': 'Junior', 'referentin qualitätssicherung': 'Junior', 'referentin recruiting / specialist recruiting': 'Junior', 'referentin unternehmenskommunikation': 'Junior', 'research analyst': 'Junior', 'research associate | ph.d. candidate': 'Junior', 'responsable achats segment logistique et achats generaux': 'Senior', 'responsable activité equipements de production et machinerie - site de cholet': 'Senior', 'responsable administration des ventes': 'Senior', 'responsable administrative direction cemmerciale france': 'Senior', 'responsable commercial': 'Senior', 'responsable commercial - ingénierie & intégration': 'Senior', 'responsable commercial et développement': 'Senior', 'responsable commercial france': 'Senior', 'responsable commercial grands comptes': 'Senior', 'responsable commercial groupe': 'Senior', 'responsable commercial zeiss industrial quality solutions': 'Senior', 'responsable commerciale & partenariats  - bemove': 'Senior', 'responsable commerciale à vivoka': 'Senior', 'responsable communication - sapa france': 'Senior', 'responsable communication & marketing digital': 'Senior', 'responsable communication et trade marketing': 'Senior', 'responsable communication marketing': 'Senior', 'responsable communications': 'Senior', 'responsable communications marketing': 'Senior', 'responsable comptabilité et contrôle de gestion': 'Senior', 'responsable coordination commerciale & fidélisation clients': 'Senior', "responsable d'agence": 'Senior', 'responsable de agencias': 'Senior', 'responsable de département infrastructure & projet': 'Senior', 'responsable de tesorería': 'Senior', 'responsable département industrie (robotique et machine spéciale)': 'Senior', 'responsable des opérations': 'Senior', "responsable des systèmes d'information": 'Senior', "responsable des systèmes d'information groupe": 'Senior', 'responsable des ventes': 'Senior', 'responsable des ventes decip machines  outils': 'Senior', 'responsable développement': 'Senior', 'responsable développement commercial': 'Senior', 'responsable développement commercial batiments industriels': 'Senior', 'responsable développement commercial chez arès business & consulting': 'Senior', 'responsable développement commercial -zone europe chez petercem sonsors': 'Senior', 'responsable développement nouveaux marchés': 'Senior', 'responsable développement santé hôpitaux et cliniques': 'Senior', 'responsable développements informatiques': 'Senior', "responsable d'exploitation du système d'information": 'Senior', 'responsable digital et e-commerce groupe': 'Senior', 'responsable digitale': 'Senior', 'responsable distribution france': 'Senior', 'responsable du développement d’activité navale et défense': 'Senior', 'responsable du développement de la communication digitale': 'Senior', 'responsable du service marketing & communication externe': 'Senior', 'responsable equipe base de données client': 'Senior', 'responsable événementiel': 'Senior', 'responsable informatique - france': 'Senior', 'responsable informatique décisionnelle': 'Senior', 'responsable informatique groupe': 'Senior', 'responsable infrastructure informatique': 'Senior', 'responsable lean manufacturing': 'Senior', 'responsable marketing - pôle marché bâtiments': 'Senior', 'responsable marketing & communication marques fca et activité moto': 'Senior', 'responsable marketing b2b': 'Senior', 'responsable marketing communication': 'Senior', 'responsable marketing et communications': 'Senior', 'responsable marketing international': 'Senior', 'responsable marketing opérationnel': 'Senior', 'responsable marketing produits': 'Senior', 'responsable marketing produits supply chain': 'Senior', 'responsable marketing stratégique': 'Senior', 'responsable marketing stratégique et stratégie internationale': 'Senior', 'responsable national des ventes france': 'Senior', 'responsable nouvelle-aquitaine': 'Senior', 'responsable pôle relation clients': 'Senior', 'responsable prescription': 'Senior', 'responsable presse et événementiel': 'Senior', 'responsable produits': 'Senior', 'responsable projets informatiques': 'Senior', 'responsable ressources humaines': 'Senior', 'responsable secteur': 'Senior', 'responsable service commercial france': 'Senior', 'responsable services généraux': 'Senior', "responsable système d'information et méthodes": 'Senior', 'responsable systèmes informatiques': 'Senior', 'security + netzwerk engineer': 'Senior', 'service desk analyst': 'Junior', 'social media referent': 'Junior', 'software engineer': 'Senior', 'solution engineer': 'Senior', 'solution engineer professional': 'Senior', 'specialty gases applications engineer': 'Senior', 'studentischer mitarbeiter nextmedia.hamburg': 'Junior', 'system engineer': 'Senior', 'systems analyst': 'Junior', 'systems engineer': 'Senior', 'team leader': 'Lead', 'team leader pre and after sales support': 'Lead', 'teamlead cross industries': 'Lead', 'teamlead customer engagement': 'Lead', 'teamlead email marketing': 'Lead', 'teamlead events': 'Lead', 'teamlead key account': 'Lead', 'teamlead strategy': 'Lead', 'teamleader': 'Lead', 'teamleader bi systems @ h.c. starck tantalum and niobium gmbh': 'Lead', 'teamleader front and back office services': 'Lead', 'teamleader resourcing center berlin': 'Lead', 'teamleader telemarketing': 'Lead', 'techn. kaufm. mitarbeiter': 'Junior', 'underwriter analyst ii': 'Junior', 'vétérinaire responsable technique de la gamme volaille': 'Senior', 'vorsitz': 'Management', 'vorsitzende': 'Management', 'vorsitzende des aufsichtsrates': 'Management', 'vorsitzender': 'Management', 'vorsitzender aufsichtsrat': 'Management', 'vorsitzender des aufsichtsrates': 'Management', 'vorsitzender des aufsichtsrates: arno walter': 'Management', 'vorsitzender des aufsichtsrates: dr. henning prüß': 'Management', 'vorsitzender des aufsichtsrates: jean-marie dayre': 'Management', 'vorsitzender des aufsichtsrats': 'Management', 'vorsitzender des beirats': 'Management', 'vorsitzender des präsidiums': 'Management', 'vorsitzender des vorstands': 'Management', 'vorstands-vorsitzender': 'Management', 'wissenschaftlicher mitarbeiter': 'Junior', 'assistent': 'Junior', 'assistent projektmanagement': 'Junior', 'assistentin': 'Junior', 'assistentin / sekretärin der gl': 'Junior', 'assistentin der gf': 'Junior', 'assistentin der gl': 'Junior', 'assistentin der institutsdirektion': 'Junior', 'assistentin des vorstandes': 'Junior', 'assistentin des vorstandsvorsitzenden': 'Junior', 'assistentin gf (hr. rummel)': 'Junior', 'assistentin produktentwicklung': 'Junior', 'assistentin technologien & märkte': 'Junior', 'assistentin verkauf & personalrekrutierung': 'Junior', 'assistentin von frau özkazanc': 'Junior', 'assistentin von meyer-voigtländer': 'Junior', 'assistentin vorstand': 'Junior', 'kaufmännische assistentin': 'Junior', 'sekretärin / assistentin': 'Junior', 'team-assistentin': 'Junior', 'analyst strategy & business development': 'Junior', 'business | technology consultant': 'Senior', 'business analyst': 'Junior', 'business analyst (sugarcrm/suitecrm)': 'Junior', 'business analyst / commercial controller': 'Junior', 'business analyst crm': 'Junior', 'business analyst crm & digital': 'Junior', 'business analyst it': 'Junior', 'business assistent / key account support': 'Junior', 'business consultant': 'Senior', 'business consultant - digital transformation bu...': 'Senior', 'business consultant crm - systeme': 'Senior', 'business consultant industry': 'Senior', 'business data analyst – sehner - international': 'Junior', 'business development & consultant lead': 'Senior', 'business development analyst': 'Junior', 'business development associate': 'Junior', 'business development consultant': 'Senior', 'business development engineer': 'Senior', 'business engineer': 'Senior', 'business intelligence & dynamics 365 (crm) consultant': 'Senior', 'business intelligence analyst': 'Junior', 'business it consultant': 'Senior', 'business process analyst': 'Junior', 'business solutions analyst': 'Junior', 'business systems analyst - operations': 'Junior', 'business systems analyst/developer (crm)': 'Junior', 'consultant sap business bydesign': 'Senior', 'crm business analyst': 'Junior', 'crm business consultant': 'Senior', 'crm/sap ict business analyst': 'Junior', 'global business process analyst - crm strategy/demand mgt.': 'Junior', 'inhouse consultant erp / business systems': 'Senior', 'it business analyst - crm': 'Junior', 'it business analyst & sap crm consultant': 'Senior', 'it business analyst crm': 'Junior', 'it business analyst sap crm': 'Junior', 'it business application analyst': 'Junior', 'it business application analyst crm': 'Junior', 'it business process analystin / projektmanagement': 'Junior', 'it team leader business applications': 'Lead', 'it-projektmanager / business process analyst': 'Junior', 'lead business analyst': 'Junior', 'lead business consultant': 'Senior', 'lead business operations analyst': 'Junior', 'teamleader business contact centre dach bei farnell gmbh': 'Lead', 'teamleader system support business controlling': 'Lead', 'zelfstandig it business analyst': 'Junior', 'analytics consultant': 'Senior', 'application consultant': 'Senior', 'application consultant wms': 'Senior', 'application services consultant (mcp / mcse)': 'Senior', 'associate consultant': 'Senior', 'client strategy consultant': 'Senior', 'consultant': 'Senior', 'consultant /system-u. netzwerkadministration': 'Senior', 'consultant and administrator': 'Senior', 'consultant digital learning solutions': 'Senior', 'consultant digital signage': 'Senior', 'consultant für prozessorientiertes wissensmanag...': 'Senior', 'consultant microsoft dynamics ax': 'Senior', 'consultant research & media innovation': 'Senior', 'consultant sap logistics/ it group': 'Senior', 'consultant system- und prozessentwicklung': 'Senior', 'consultant/ customer service advisor': 'Senior', 'customer success consultant': 'Senior', 'd365 / power platform technical consultant': 'Senior', 'data analyst & consultant': 'Senior', 'development consultant': 'Senior', 'digital consultant': 'Senior', 'digital transformation consultant': 'Senior', 'digitalization consultant': 'Senior', 'ediscovery consultant': 'Senior', 'engineering consultant': 'Senior', 'entrepreneur & consultant': 'Senior', 'erp consultant': 'Senior', 'hr consultant': 'Senior', 'inhouse bi consultant': 'Senior', 'inhouse consultant erp': 'Senior', 'inhouse erp consultant': 'Senior', 'internal sharepoint consultant - it-admin': 'Senior', 'international consultant online recruitment': 'Senior', 'it consultant': 'Senior', 'it consultant - pmo': 'Senior', 'it-consultant': 'Senior', 'it-consultant / systembetreuer microsoft dynamics nav': 'Senior', 'it-services consultant': 'Senior', 'leading consultant': 'Senior', 'meetings & events consultant': 'Senior', 'mergers and acquisitions consultant': 'Senior', 'microsoft dynamics nav - consultant & microsoft certified trainer': 'Senior', 'microsoft dynamics nav consultant & trainer': 'Senior', 'microsoft dynamics nav entwicklung/ consultant': 'Senior', 'ms dynamics consultant': 'Senior', 'online reputation consultant @ provenexpert': 'Senior', 'pr consultant': 'Senior', 'presales consultant': 'Senior', 'principal consultant': 'Senior', 'principal solutions consultant emea': 'Senior', 'project consultant': 'Senior', 'projektmanager / consultant': 'Senior', 'real estate consultant': 'Senior', 'recruitment consultant': 'Senior', 'recruitment consultant & social media planer': 'Senior', 'recruitment von it consultants und professionals': 'Senior', 'research consultant': 'Senior', 'sap applications consultant sd/mm': 'Senior', 'sap beraterin / sap consultant': 'Senior', 'sap bi/bw inhouse consultant': 'Senior', 'sap bw inhouse consultant': 'Senior', 'sap c4c consultant': 'Senior', 'sap consultant': 'Senior', 'sap consultant sd': 'Senior', 'sap it consultant': 'Senior', 'sap sd consultant': 'Senior', 'sap sd/cs/cem inhouse consultant': 'Senior', 'sap technology consultant': 'Senior', 'sap-consultant': 'Senior', 'search consultant': 'Senior', 'social media & web2.0 consultant': 'Senior', 'solution consultant': 'Senior', 'solutions consultant': 'Senior', 'talent consultant': 'Senior', 'technical consultant': 'Senior', 'technologie services consultant': 'Senior', 'technology consultant': 'Senior', 'trainer / consultant': 'Senior', 'user experience & creative recruitment consultant': 'Senior', 'zertifizierter itsm consultant': 'Senior', 'gl und hr assistentin': 'Junior', 'hr assistentin': 'Junior', '3rd level it engineer': 'Senior', 'associate distribution administration germany and austria': 'Junior', 'chef de projet digital client': 'Lead', 'chef de projet it moe': 'Lead', 'digital data analyst': 'Junior', 'digital process engineer': 'Senior', 'engineer / systems administrator': 'Senior', 'ingénieur webmarketing et responsable administration des ventes': 'Senior', 'it analyst': 'Junior', 'it assistent': 'Junior', 'it lead engineer': 'Senior', 'it mitarbeiter': 'Junior', 'it solution analyst': 'Junior', 'it system engineer': 'Senior', 'it system engineer mobility': 'Senior', 'it teamleader': 'Lead', 'it-system engineer': 'Senior', 'mitarbeiter it infrastructure': 'Junior', 'referent digital & innovation': 'Junior', 'referentin it solutions': 'Junior', 'responsable application dynamics 365 / reporting power bi - sap/bo': 'Senior', 'responsable commercial & marketing solutions digitales': 'Senior', 'responsable it groupe': 'Senior', 'teamlead digital platform': 'Lead', 'teamlead it-services': 'Lead', 'teamleader group it - shared technology services': 'Lead', 'teamleader it applications': 'Lead', 'teamleader it connectivity': 'Lead', 'b2b crm consultant': 'Senior', 'chef de projet commerce / crm': 'Lead', 'chef de projet crm': 'Lead', 'chef de projet crm & retention': 'Lead', 'chef de projet crm et performance commerciale (réseau agents généraux)': 'Lead', 'chef de projet crm fidélisation': 'Lead', 'chef de projet crm senior': 'Lead', 'chef de projet digital & crm': 'Lead', 'chef de projet digital/crm': 'Lead', 'chef de projet informatique - responsable applicatif outils crm': 'Senior', 'chef de projet moa sap - crm cloud for customer': 'Lead', 'chef de projets crm': 'Lead', 'consultant (data scientist/crm)': 'Senior', 'consultant crm & web': 'Senior', 'consultant it corporate applications crm': 'Senior', 'crm & bi consultant': 'Senior', 'crm analyst': 'Junior', 'crm application consultant international': 'Senior', 'crm applications analyst': 'Junior', 'crm consultant': 'Senior', 'crm consultant/analyst': 'Senior', 'crm data & process engineer': 'Senior', 'crm engagement lead': 'Lead', 'crm global project leader': 'Lead', 'crm inhouse consultant': 'Senior', 'crm it consultant': 'Senior', 'crm-/ bpm - consultant': 'Senior', 'crm-analystin': 'Junior', 'domainlead it crm': 'Lead', 'functional analyst sap crm': 'Junior', 'inhouse consultant dynamics crm': 'Senior', 'inhouse consultant sap crm': 'Senior', 'inhouse consultant sd/crm': 'Senior', 'inhouse crm consultant': 'Senior', 'insightly crm expert - consultant': 'Senior', 'it analyst crm': 'Junior', 'it inhouse consultant crm': 'Senior', 'it-consultant crm-solutions': 'Senior', 'it-system analyst - crm / innovationsexperte': 'Junior', 'microsoft dynamics crm inhouse consultant': 'Senior', 'package solution consultant (crm)': 'Senior', 'referent crm': 'Junior', 'referent crm / network development': 'Junior', 'referent crm-system': 'Junior', 'responsable animation commerciale/ crm': 'Senior', 'responsable crm': 'Senior', 'responsable crm & back office france': 'Senior', 'responsable crm & e-commerce': 'Senior', 'responsable crm chez crm services - sncf voyages': 'Senior', 'responsable crm et fidélisation': 'Senior', 'responsable crm groupe isaltis': 'Senior', 'responsable crm maximizer': 'Senior', 'responsable d’application crm et clients': 'Senior', 'responsable data & crm': 'Senior', 'responsable data client & crm': 'Senior', 'responsable data management et crm': 'Senior', 'responsable des ventes - bu crm': 'Senior', 'responsable domaine crm': 'Senior', 'responsable formation et referent crm': 'Junior', 'responsable projet et communauté crm': 'Senior', 'responsable projets crm': 'Senior', 'responsable sfe et crm- france': 'Senior', 'responsable si outils (crm)': 'Senior', 'sap and crm solutions consultant - customer relations': 'Senior', 'sap consultant - crm & sd (implementation project)': 'Senior', 'sap consultant crm': 'Senior', 'sap crm & cec consultant': 'Senior', 'sap crm consultant': 'Sen

In [35]:
# Feature Text

TEXT_COLS = ["position", "organization"]

df_active["text"] = (
    df_active[TEXT_COLS]
    .fillna("")
    .agg(" ".join, axis=1)
    .str.lower()
)

In [36]:
# Matching Dictionaries

def dict_match(text, label_dict):
    for keyword, label in label_dict.items():
        if keyword in text:
            return label
    return np.nan

In [37]:
# Application on Annotated CVs

df_active["pred_department"] = df_active["text"].apply(
    lambda x: dict_match(x, department_dict)
)

df_active["pred_seniority"] = df_active["text"].apply(
    lambda x: dict_match(x, seniority_dict)
)

In [38]:
#Successful Classification
dept_coverage = df_active["pred_department"].notna().mean()
sen_coverage = df_active["pred_seniority"].notna().mean()

print(f"Department Coverage: {dept_coverage:.2%}")
print(f"Seniority Coverage: {sen_coverage:.2%}")

Department Coverage: 40.93%
Seniority Coverage: 62.12%

In [40]:
#Accuracy with assigned labels for Department
dept_eval = df_active.dropna(
    subset=["department", "pred_department"]
)

dept_accuracy = (
    dept_eval["department"] == dept_eval["pred_department"]
).mean()

print(f"Department Accuracy: {dept_accuracy:.2%}")

Department Accuracy: 39.61%

In [43]:
#Accuracy with assigned labels for Department
sen_eval = df_active.dropna(
    subset=["seniority", "pred_seniority"]
)

sen_accuracy = (
    sen_eval["seniority"] == sen_eval["pred_seniority"]
).mean()

print(f"Seniority Accuracy: {sen_accuracy:.2%}")

Seniority Accuracy: 57.11%